env:
  browser: true
  es2021: true
  node: true
root: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - eslint-config-postcss
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: 'off'
  'prefer-let/prefer-let': 'off'
  no-shadow: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
ignorePatterns:
  - .github
  - .nyc_output
  - .vscode
  - coverage
  - dist
  - node_modules
